### ISSUE TITLE
Html button in popper

### ISSUE THREAD

**Issue by chrisooo3** [andreivictor/bootstrap-tooltip-custom-class#19]
Hi, 
why the button does not render?
My files look like: 
```html
<button class="btn btn-secondary js-btn-popover--custom-alt" data-toggle="popover" data-trigger="focus" data-placement="bottom" title="Another custom popover" data-content="Button: <button>Try</button>">Another custom popover</button>
```

```js
$(document).ready(function(){
  
  $('.js-btn-popover--custom-alt').popover({
    customClass: 'popover-custom-alt',
    html: true,
  });
});
```

**Comment by andreivictor** [comment]
This is not related to BootstrapTooltipCustomClass. This extension does not interfere with the other options available for Bootstrap popover.

Bootstrap Tooltips and Popovers use a built-in sanitizer to sanitize options which accept HTML.
For v4:
https://getbootstrap.com/docs/4.3/getting-started/javascript/#sanitizer

As you can see from the list above, the `button` tag is not whitelisted - so it is removed before displaying the popover.

At this point, you have two options:

- _quick&dirty_: disable sanitizer completely, via `sanitize: false` option:
 
 `$('.btn-custom-alt').popover({
    customClass: 'popover-custom-alt',
    html: true,
    sanitize: false
  });`

- _recommended_: add the `button` tag to the whitelist, as described in the link above:
`var myDefaultWhiteList = $.fn.tooltip.Constructor.Default.whiteList

// To allow button elements
myDefaultWhiteList.button = []`

example: https://codepen.io/andreivictor/pen/qBaLpgV
